---
title: Fancy knitr
author: Tianyi Shi
date: '2020-03-23'
slug: fancy-knitr
categories:
  - r
tags:
  - knitr
---

# **knitr** Supports Many More Languages Than You Might Expect

Although it's easy to insert R/Python/SQL/Bash/Rcpp/D3/Stan code chunks using RStudio's GUI, many more languages are supported. The following commmand lists all languages available:

```{r}
names(knitr::knit_engines$get())
```

Here I wrote a simple function in Rcpp that finds the nth fibonacci number.

```{Rcpp}
#include <Rcpp.h>

// [[Rcpp::export]]
int fibonacci(const int x) {
  if (x == 0 || x == 1) return(x);
  return (fibonacci(x-1) + fibonacci(x - 2));
}
```

Then I can call it in an R code chunk:

```{r}
fibonacci(10L)
```


```{node}
console.log({result: "hello world"})
```

```{go engine.path="/usr/local/go/bin/go"                                                                                                                                                                                                                     }
package main
import "fmt"
func main() {
  fmt.Println("Hello world!")
}
```

