---
title: Adding Support for Rust in knitr (R Markdown)
author: Tianyi Shi
date: '2020-03-23'
slug: adding-support-for-rust-in-knitr-r-markdown
categories:
  - r
tags:
  - knitr
---

R Markdown is a great tool for authoring documents that can be seamlessly rendered into various output formats. One of the best feature of R Markdown is being able to execute code chunks and format their output, which is backended by the **knitr** package. Although R, Python and SQL get more support for this feature, many other languages are also supported. This is usually achieved by evaluating the code in the code chunk using the corresponding engine in shell (where compilation is needed, a temporary binary is generated) and formatting the output retrieved from stdout. 

The languages supported by **knitr** can be shown using this command:

```{r}
names(knitr::knit_engines$get())
```


As of 23 Feb 2020, Rust is not supported. Rust has been voted the most-loved language for the past four years in StackOverflow's annual developer surveys. I recently also fell in love with Rust, and I wanted to write notes on Rust with blogdown. 