baseurl = "/"
languageCode = "en-us"
title = "Tianyi as a Developer"
publishDir = "docs"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "R"
    url = "/r/"
[[menu.main]]
    name = "JS"
    url = "/js/"
[[menu.main]]
    name = "Rust"
    url = "/rust/"
[[menu.main]]
    name = "Python"
    url = "/python/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/TianyiShi2001"


[params]
    description = "Tianyi's Blog on Programming"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "rust", "javascript", "python", "bash"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

